---

- name: Configure L2 Vlans
  with_items: "{{ vlans }}"
  cisco.ios.ios_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.id }}"
    state: replaced

- name: Configure L3 Vlans
  with_items: "{{ vlans }}"
  when: "'core' in group_names"
  cisco.ios.ios_config:
    parents: interface Vlan{{ item.id }}
    lines:
      - ip address {{ item.address }} {{ item.mask }}

- name: Enable L3 Vlans
  with_items: "{{ vlans }}"
  when: "'core' in group_names"
  cisco.ios.ios_interfaces:
    config:
      - name: Vlan{{ item.id }}
        enabled: true
    state: replaced